packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@monaco-editor/react": ^4.7.0
  "@types/node": ^24
  monaco-editor: ^0.55.1
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  webgal-parser: ^4.5.18

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
