name: Deploy Playground

on:
  push:
    branches: [master]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      - run: vp install
      - run: vp check --fix
      - run: vp test
      - name: Build with Playground
        run: vp run build
        env:
          GITHUB_PAGES: true # 传递环境变量，和本地一致
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/playground/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
